services:
  ble-ip-scanner:
    image: alpine:3.20
    container_name: ble-ip-scanner
    network_mode: host
    privileged: true
    restart: unless-stopped

    volumes:
      - /your-path/presence/app:/app

    environment:
      gitbranch: 'development'   # GitHub branch 'main' or 'development'
      gitupdate: 'n'             # Force github update at startup container

    working_dir: /app

    command: >
      sh ./startup.sh