services:
  ble_ip_scanner:
    image: jvdzande/ble_ip_scanner
    container_name: ble_ip_scanner
    network_mode: host
    privileged: true
    restart: unless-stopped

    environment:
      TZ: 'Europe/Amsterdam'
      #hci_device: 'hci0'       # default: hci0

    volumes:
      - /your-path/presence/app/config:/app/config
      - /your-path/presence/app/log:/app/log
